### ISSUE TITLE
is it really ruby 2.2.0 required?

### ISSUE THREAD

**Issue by qinghe** [groundctrl/proclaimer#20]
why require ruby 2.2.0, is ruby 2.1 supported?

**Comment by vinniefranco** [comment]
@qinghe Tests are ran against 2.1 and 2.2, I'll lower the gemspec and make another release to lessen the version requirement.

**Comment by vinniefranco** [comment]
@qinghe `0.3.1` just released to allow 2.1+ instead of 2.2+, thanks for reaching out!

**Comment by qinghe** [comment]
Thanks  @vinniefranco
